import Head from "next/head";
import { useEffect } from "react";
import List from "./List";
// import { api } from "~/utils/api";

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  useEffect(() => {
    document.body.className = "bg-charcoal-700";
  });

  return (
    <>
      <Head>
        <title>Task Stack</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col max-h-screen overflow-hidden">
        <div className="bg-charcoal-800 p-5 text-center">
          <h1 className="text-2xl font-bold tracking-wide text-white">
            Task Stack
          </h1>
        </div>
        <main className="flex space-x-2 pt-5 mx-3 text-white overflow-x-scroll overflow-y-hidden h-screen">
          <List heading="List"></List>
          <List heading="List1"></List>
          <List heading="3ist1"></List>
          <List heading="4ist1"></List>
          <List heading="4ist1"></List>
          {/* <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p> */}
        </main>
      </div>
    </>
  );
}
